# Generated by Django 5.0 on 2024-03-02 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_delete_student_delete_teacher_and_more'),
        ('classes', '0001_initial'),
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='day_of_week',
            field=models.CharField(blank=True, choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Entire Week', 'For Entire Week')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='routine',
            name='target_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.class'),
        ),
    ]
