# Generated by Django 5.0 on 2024-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RFID',
            fields=[
                ('rfid_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
