# Generated by Django 5.0 on 2024-03-15 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0002_rfid_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='created_at',
        ),
    ]
