# Generated by Django 5.0 on 2024-03-15 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RFID', '0003_remove_rfid_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
