# Generated by Django 5.0 on 2024-04-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='assigned_class_name',
            field=models.TextField(null=True),
        ),
    ]
