# Generated by Django 5.0 on 2024-04-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_rfid_number_alter_teacher_rfid_number'),
        ('leave_requests', '0003_remove_leaverequest_assigned_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='students',
            field=models.ManyToManyField(related_name='student-leave+', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher-leave+', to='accounts.teacher'),
        ),
    ]
