# Generated by Django 5.0 on 2024-04-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_requests', '0004_leaverequest_students_leaverequest_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='students',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='teachers',
        ),
    ]
