# Generated by Django 5.0 on 2024-04-04 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='teachers',
            field=models.ManyToManyField(related_name='teacher_chat_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
