# Generated by Django 5.0 on 2024-04-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_rfid_number_alter_teacher_rfid_number'),
        ('chat', '0003_chatroom_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='teachers',
            field=models.ManyToManyField(to='accounts.teacher'),
        ),
    ]
