# Generated by Django 5.0 on 2024-04-10 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_rfid_number_alter_teacher_rfid_number'),
        ('chat', '0004_alter_chatroom_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='teachers',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='students',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='teachers',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher'),
        ),
    ]
