# Generated by Django 5.0 on 2024-04-10 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_chatroom_students_remove_chatroom_teachers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='latest_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_message_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='sender_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='chat_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom'),
        ),
    ]
