# Generated by Django 5.0 on 2024-04-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_rfid_number_alter_teacher_rfid_number'),
        ('chat', '0006_remove_chatroom_latest_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='students',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='teachers',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='students',
            field=models.ManyToManyField(null=True, to='accounts.student'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='teachers',
            field=models.ManyToManyField(null=True, to='accounts.teacher'),
        ),
    ]
