# Generated by Django 5.0 on 2024-04-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_student_rfid_number_alter_teacher_rfid_number'),
        ('chat', '0007_remove_chatroom_students_remove_chatroom_teachers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='teachers',
            field=models.ManyToManyField(to='accounts.teacher'),
        ),
    ]
