# Generated by Django 5.0 on 2024-03-02 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_delete_student_delete_teacher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='identity_number',
            new_name='rfid_number',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='identity_number',
            new_name='rfid_number',
        ),
    ]
