# Generated by Django 5.0 on 2024-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_identity_number_student_rfid_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_class',
            new_name='assigned_class',
        ),
    ]
