# Generated by Django 5.0 on 2024-03-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_apikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='device_name',
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
