# Generated by Django 5.0 on 2024-04-20 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_target_class_alter_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 21, 42, 56, 123885)),
        ),
    ]
