# Generated by Django 5.0 on 2024-04-20 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_alter_announcement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 20, 23, 50, 33, 95728)),
        ),
    ]
