# Generated by Django 5.0 on 2024-04-20 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_alter_announcement_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 21, 0, 0, 18, 161633)),
        ),
    ]
