# Generated by Django 5.0 on 2024-04-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_alter_attendance_date_alter_attendance_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='entry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
