# Generated by Django 5.0 on 2024-04-20 18:34

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_alter_attendance_entry_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=attendance.models.get_current_nepali_date),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
